### ISSUE TITLE
Error Pylama

### ISSUE THREAD

**Issue by RobotXP** [AtomLinter/linter-pylama#73] opened 2017-05-01 19:32 UTC
Hello,

Currently with Atom 1.6.0 installed, I decided to install the linter-pylama package and I get this message whenever I type anything ....

http://ap.imagensbrasil.org/image/jNeyw6

I have tried to uninstall linter-pylama and Atom and reinstall, but it does not work, I tried to install another linter, but it also does not work, what do I do?

**Comment by ddaanet** [comment] 2017-05-06 18:01
I guess you are having the same problem I have with external pylama. PR #74

**Comment by ddaanet** [comment] 2017-05-06 18:02
Duplicate of #62

**Comment by ddaanet** [comment] 2017-05-11 08:51
@RobotXP do you still have this problem with `linter-pylama` 0.8.19?

**Closed** 2017-05-15 08:06 UTC
